//CRUD
//C -STUDENTS
//C -INITIAL BILLS
//C -SIMULATING TIME PASSING SO BILLS AUTOMATICALLY GENERATE

//R -READING STUDENTS INFO THAT HAS BEEN SIMULATED
//R -READING INDIVIDUAL STUDENT DETAILS

//U - STUDENT DATA WE ARE ALLOWED TO UPDATE
//U - DATA

//D - DELETING DATA THAT IS IRRELEVANT TO BILLING
//D - ENSURE THAT A STUDENT WITH MORE THAN 1 MONTH OF BILLING IS NOT DELETED